iata_codes = {
    # Western Europe
    "Paris": "PAR",
    "Nice": "NCE",
    "Lyon": "LYS",
    "Marseille": "MRS",
    "Bordeaux": "BOD",
    "Toulouse": "TLS",
    "Nantes": "NTE",
    "Strasbourg": "SXB",
    "Amsterdam": "AMS",
    "Rotterdam": "RTM",
    "Eindhoven": "EIN",
    "Brussels": "BRU",
    "Antwerp": "ANR",
    "Bruges": "OST",
    "Luxembourg": "LUX",
    # Southern Europe
    "Rome": "ROM",
    "Milan": "MIL",
    "Venice": "VCE",
    "Florence": "FLR",
    "Naples": "NAP",
    "Bologna": "BLQ",
    "Pisa": "PSA",
    "Turin": "TRN",
    "Palermo": "PMO",
    "Catania": "CTA",
    "Madrid": "MAD",
    "Barcelona": "BCN",
    "Seville": "SVQ",
    "Valencia": "VLC",
    "Malaga": "AGP",
    "Alicante": "ALC",
    "Bilbao": "BIO",
    "Ibiza": "IBZ",
    "Mallorca": "PMI",
    "Tenerife": "TCI",
    "Lisbon": "LIS",
    "Porto": "OPO",
    "Faro": "FAO",
    "Madeira": "FNC",
    "Ponta Delgada": "PDL",
    "Athens": "ATH",
    "Thessaloniki": "SKG",
    "Santorini": "JTR",
    "Mykonos": "JMK",
    "Crete": "HER",
    "Rhodes": "RHO",
    "Corfu": "CFU",
    "Malta": "MLA",
    "Valletta": "MLA",
    # Central Europe
    "Berlin": "BER",
    "Munich": "MUC",
    "Frankfurt": "FRA",
    "Hamburg": "HAM",
    "Cologne": "CGN",
    "Dusseldorf": "DUS",
    "Stuttgart": "STR",
    "Nuremberg": "NUE",
    "Hannover": "HAJ",
    "Vienna": "VIE",
    "Salzburg": "SZG",
    "Innsbruck": "INN",
    "Zurich": "ZRH",
    "Geneva": "GVA",
    "Basel": "BSL",
    "Bern": "BRN",
    "Prague": "PRG",
    "Budapest": "BUD",
    "Warsaw": "WAW",
    "Krakow": "KRK",
    "Gdansk": "GDN",
    "Wroclaw": "WRO",
    "Bratislava": "BTS",
    # UK & Ireland
    "London": "LON",
    "Edinburgh": "EDI",
    "Glasgow": "GLA",
    "Manchester": "MAN",
    "Birmingham": "BHX",
    "Bristol": "BRS",
    "Liverpool": "LPL",
    "Belfast": "BFS",
    "Newcastle": "NCL",
    "Leeds": "LBA",
    "Dublin": "DUB",
    "Cork": "ORK",
    "Shannon": "SNN",
    # Northern Europe
    "Copenhagen": "CPH",
    "Billund": "BLL",
    "Aarhus": "AAR",
    "Stockholm": "STO",
    "Gothenburg": "GOT",
    "Malmo": "MMX",
    "Oslo": "OSL",
    "Bergen": "BGO",
    "Stavanger": "SVG",
    "Trondheim": "TRD",
    "Tromso": "TOS",
    "Helsinki": "HEL",
    "Rovaniemi": "RVN",
    "Reykjavik": "REK",
    "Riga": "RIX",
    "Tallinn": "TLL",
    "Vilnius": "VNO",
    "Kaunas": "KUN",
    # Eastern & Southeastern Europe
    "Bucharest": "BUH",
    "Cluj": "CLJ",
    "Sofia": "SOF",
    "Varna": "VAR",
    "Belgrade": "BEG",
    "Zagreb": "ZAG",
    "Split": "SPU",
    "Dubrovnik": "DBV",
    "Zadar": "ZAD",
    "Ljubljana": "LJU",
    "Sarajevo": "SJJ",
    "Skopje": "SKP",
    "Tirana": "TIA",
    "Podgorica": "TGD",
    "Istanbul": "IST",
    "Antalya": "AYT",
    "Cyprus": "LCA",
    "Larnaca": "LCA",
    "Paphos": "PFO",
    # Global Hubs
    "New York": "NYC",
    "Los Angeles": "LAX",
    "Chicago": "CHI",
    "Dubai": "DXB",
    # Top 50 European Countries & Microstates (Mapped to primary hub for the flight widget)
    "Albania": "TIA",
    "Andorra": "BCN",  # No airport; Barcelona is closest hub
    "Armenia": "EVN",
    "Austria": "VIE",
    "Azerbaijan": "GYD",
    "Belgium": "BRU",
    "Bosnia and Herzegovina": "SJJ",
    "Bulgaria": "SOF",
    "Croatia": "ZAG",
    "Cyprus": "LCA",
    "Czech Republic": "PRG",
    "Denmark": "CPH",
    "Estonia": "TLL",
    "Faroe Islands": "FAE",
    "Finland": "HEL",
    "France": "PAR",
    "Georgia": "TBS",
    "Germany": "FRA",
    "Gibraltar": "GIB",
    "Greece": "ATH",
    "Hungary": "BUD",
    "Iceland": "KEF",
    "Ireland": "DUB",
    "Italy": "ROM",
    "Kosovo": "PRN",
    "Latvia": "RIX",
    "Liechtenstein": "ZRH",  # No airport; Zurich is closest hub
    "Lithuania": "VNO",
    "Luxembourg": "LUX",
    "Malta": "MLA",
    "Moldova": "KIV",
    "Monaco": "NCE",  # No airport; Nice is closest hub
    "Montenegro": "TGD",
    "Netherlands": "AMS",
    "North Macedonia": "SKP",
    "Norway": "OSL",
    "Poland": "WAW",
    "Portugal": "LIS",
    "Romania": "OTP",
    "San Marino": "BLQ",  # No airport; Bologna is closest hub
    "Serbia": "BEG",
    "Slovakia": "BTS",
    "Slovenia": "LJU",
    "Spain": "MAD",
    "Sweden": "STO",
    "Switzerland": "ZRH",
    "Turkey": "IST",
    "United Kingdom": "LON",
    "Vatican City": "ROM",  # No airport; Rome is closest hub
}

# Premium curated images for top destinations (3 per location)
destination_images = {
    "Paris": [
        "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",  # Eiffel
        "https://images.unsplash.com/photo-1499856871958-5b9627545d1a",  # Louvre
        "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f",  # Streets
    ],
    "London": [
        "https://images.unsplash.com/photo-1533929736458-ca588d08c8be",  # Big Ben
        "https://images.unsplash.com/photo-1520986606214-8b456906c813",  # Phone Box
        "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad",  # Streets
    ],
    "Italy": [
        "https://images.unsplash.com/photo-1516483638261-f4dafaf00bc2",  # Cinque Terre
        "https://images.unsplash.com/photo-1525874684015-58379d421a52",  # Florence
        "https://images.unsplash.com/photo-1514890547357-a9ee288728e0",  # Venice
    ],
    "Default": [
        "https://images.unsplash.com/photo-1467269204594-9661b134dd2b",  # Europe Landscape
        "https://images.unsplash.com/photo-1519677100203-a0e668c92439",  # Cafe
        "https://images.unsplash.com/photo-1499856871958-5b9627545d1a",  # Architecture
    ],
}
